name: 🚀 Deploy to FTP

on:
  push:
    branches:
      - main   # شاخه‌ای که روی آن کار می‌کنی

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          # مسیر محلی نسبت به ریشه مخزن
          local-dir: ./
          # مسیر مقصد روی هاست (مطابق ساختار وردپرس روی هاست)
          server-dir: /home/farlir/domains/farl.ir/public_html/salnama/wp-content/themes/salnama-theme-new/